# Numpy

In [1]:
import numpy as np
A = [1,2,3,4,5,6,7,8,9,10]

np.array(A)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [2]:
B = [[4,5,6],[7,8,9],[10,11,12]]

np.array(B)

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [3]:
np.arange(0,40,5)

array([ 0,  5, 10, 15, 20, 25, 30, 35])

### Zero Matrices

In [4]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

### Ones Matrices

In [5]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [6]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

### Identity Matrices

In [7]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

### .linspace() 

In [8]:
np.linspace(0,20,10) # Ten (10) linearly spaced elements, starting from 0 till 20

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

# Random number generation

In [9]:
seed = 100
np.random.seed(seed)
np.random.rand(5)

array([0.54340494, 0.27836939, 0.42451759, 0.84477613, 0.00471886])

In [10]:
seed=100
np.random.seed(seed)
np.random.rand(5,5) # generate random values for 5 rows and 5 colums matrix 

array([[0.54340494, 0.27836939, 0.42451759, 0.84477613, 0.00471886],
       [0.12156912, 0.67074908, 0.82585276, 0.13670659, 0.57509333],
       [0.89132195, 0.20920212, 0.18532822, 0.10837689, 0.21969749],
       [0.97862378, 0.81168315, 0.17194101, 0.81622475, 0.27407375],
       [0.43170418, 0.94002982, 0.81764938, 0.33611195, 0.17541045]])

In [11]:
seed=100
np.random.seed(seed)
np.random.randn(5)

array([-1.74976547,  0.3426804 ,  1.1530358 , -0.25243604,  0.98132079])

In [12]:
seed=100
np.random.seed(seed)
np.random.randn(5,5) # generate random normal distribution values for 5 rows and 5 colums matrix 

array([[-1.74976547,  0.3426804 ,  1.1530358 , -0.25243604,  0.98132079],
       [ 0.51421884,  0.22117967, -1.07004333, -0.18949583,  0.25500144],
       [-0.45802699,  0.43516349, -0.58359505,  0.81684707,  0.67272081],
       [-0.10441114, -0.53128038,  1.02973269, -0.43813562, -1.11831825],
       [ 1.61898166,  1.54160517, -0.25187914, -0.84243574,  0.18451869]])

In [13]:
np.random.randint(1,500,10) # generate ten (10) random integers from number 1 to 500

array([ 14, 107,  31,  18,  54,  69, 435, 489, 348, 476])

In [14]:
A = np.arange(20,30) # generate an array of numbers, starting with 20 till 29 (input number 30 is excluded)

A.reshape(5,2) 

array([[20, 21],
       [22, 23],
       [24, 25],
       [26, 27],
       [28, 29]])

# Numpy indexing and selection

In [15]:
X = np.arange(30,41)

X

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40])

In [16]:
X[0:7]

array([30, 31, 32, 33, 34, 35, 36])

In [17]:
X[:]

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40])

In [18]:
X[2:]

array([32, 33, 34, 35, 36, 37, 38, 39, 40])

In [19]:
Y = X.copy()*2 # .copy() is basically a method to copy the variable of attached variable

Y

array([60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80])

In [20]:
Y[0:5] = 1000

Y

array([1000, 1000, 1000, 1000, 1000,   70,   72,   74,   76,   78,   80])

In [21]:
array_2d = np.array([[50,52,54],[56,58,60],[62,64,66],[68,70,72]]) # double [] indicates the dimensions of the array

array_2d

array([[50, 52, 54],
       [56, 58, 60],
       [62, 64, 66],
       [68, 70, 72]])

In [22]:
array_2d[2,1]

64

In [23]:
array_2d[2:,1:]

array([[64, 66],
       [70, 72]])

In [24]:
array_2d[3,0:2]

array([68, 70])